EVENTS = {
    ON_DATABASE_CONNECTED = "onDatabaseConnected",
    ON_RESOURCE_START = "onResourceStart",
    ON_COLSHAPE_HIT = "onColShapeHit",
    ON_COLSHAPE_LEAVE = "onColShapeLeave",
    INVENTORY = {
        ON_INVENTORY_DATABASE_CONNECTED = "onInventoryDatabaseConnected",
        ON_INVENTORY_TOGGLED = "onInventoryToggled",
        ON_ITEM_ADDED = "onItemAdded",
        ON_ITEM_REMOVED = "onItemRemoved",
        ON_ITEM_UPDATED = "onItemUpdated",
    },
    HOUSES = {
        ON_HOUSE_DATABASE_CONNECTED = "onHouseDatabaseConnected",
    },
    ACCOUNTS = {
        ON_ACCOUNT_DATABASE_CONNECTED = "onAccountDatabaseConnected",
        LOGIN_ACCOUNT = "loginAccount",
        REGISTER_ACCOUNT = "registerAccount",
    },
    CHARACTERS = {
        ON_CHARACTER_DATABASE_CONNECTED = "onCharacterDatabaseConnected",
        ON_CHARACTER_SELECTED = "onCharacterSelected",
        ON_CHARACTER_CREATED = "onCharacterCreated",
        ON_CHARACTER_DELETED = "onCharacterDeleted",
        OPEN_CHARACTER_SELECTION = "openCharacterSelection",
        OPEN_CHARACTER_CREATION = "openCharacterCreation",
        ON_CHARACTER_CREATION_COMPLETED = "onCharacterCreationCompleted",
    },
    VEHICLES = {
        OPEN_VEHICLE_SELECTION = "openVehicleSelection",
        ON_VEHICLE_SELECTED = "onVehicleSelected",
        ON_VEHICLE_PURCHASED = "onVehiclePurchased",
        ON_VEHICLE_SOLD = "onVehicleSold",
        ON_VEHICLE_MENU_OPENED = "onVehicleMenuOpened",
        ON_VEHICLE_ACTIONS_MENU_OPENED = "onVehicleActionsMenuOpened",
        ON_PLAYER_TOGGLE_ENGINE = "onPlayerToggleEngine",
        ON_PLAYER_TOGGLE_LOCK = "onPlayerToggleLock",
        ON_PLAYER_USE_HORN = "onPlayerUseHorn",
        ON_PLAYER_REFUEL_VEHICLE = "onPlayerRefuelVehicle",
    },
    GUI = {
        ON_GUI_CLICK = "onClientGUIClick",
        ON_GUI_DOUBLE_CLICK = "onClientGUIDoubleClick",
        ON_GUI_KEY_DOWN = "onClientGUIKeyDown",
        CLEAR_LOGIN_WINDOW = "clearLoginWindow",
        CLEAR_CHARACTER_SELECTION_WINDOW = "clearCharacterSelectionWindow",
        CLEAR_VEHICLE_SELECTION_WINDOW = "clearVehicleSelectionWindow",
        ON_INVENTORY_TOGGLED = "onInventoryToggled",
    }
}