services:
  mta-server:
    build: .
    develop:
        watch:
            - action: sync+restart
              path: .
              target: /opt/mta/mods/deathmatch/resources/[gamemodes]/phantomplay
            #   ignore:
            #     - meta.xml
            #     - mta-server.conf
            #     - Dockerfile
            # - action: rebuild
            #   path: meta.xml
            # - action: rebuild
            #   path: mta-server.conf
    container_name: mta_server
    ports:
      - "22003:22003/udp"
      - "22126:22126"
      - "22005:22005"
    depends_on:
      - db
    networks:
      - db_network

  db:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mta_sa
      MYSQL_USER: my_user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - db_network

volumes:
  db_data:

networks:
  db_network:
    driver: bridge
